### ISSUE TITLE
[CRASH] System.IndexOutOfRangeException: Index was outside the bounds of the array

### ISSUE THREAD

**Issue by MaxWasUnavailable** [SpearAndFang/primitive-survival#7]
```
Running on 64 bit Windows with 32689 MB RAM
Game Version: v1.18.15 (Stable)
14/01/2024 23:46:44: Critical error occurred in the following mod: primitivesurvival@3.3.0
Loaded Mods: aculinaryartillery@1.0.15, atwatersedge@1.3.1, betterruins@0.2.4, chiseltools@1.10.0, compass2@2.0.0, decor@1.0.8, fieldsofgold@2.1.6, floralzonescaribbeanregion@1.0.2, geoaddons@1.2.0, indappledgroves@0.4.10-dev.7, millwright@1.1.1, palisademod@1.1.0, pipeleaf@1.3.0, primitivesurvival@3.3.0, rpvoicechat@2.3.7, spyglass@0.5.0, thetwelvekeys@1.1.1, game@1.18.15, wildcraft@1.6.6, alchemy@1.6.21, ancienttools@1.5.11, animalcages@2.2.0, bulwark@0.0.8, butchering@1.2.2, canjewelry@0.1.24, carryon@1.6.1, coinage@1.9.0, commonlib@2.2.0, coolinbarrel@0.5.3, decoclock@0.9.1, divisionoflabor@1.0.8, electricity@0.0.10, expandedfoods@1.6.8, extrachutes@1.0.0, fancyplanters@1.2.0, fromgoldencombs@1.4.25, hudclock@3.3.0, sailboat@1.2.4, lavoisier@1.3.0, liquidcontainers@1.2.0, medievalexpansion@3.11.1, medievalmap@1.4.1, morepiles@1.4.3, petai@1.8.1, claywheel@1.1.0, prospecttogether@1.2.4, rivers@1.1.2, rustyshell@0.0.11, sabreauclair@0.0.14, scarecrow@1.3.1, storageoptions@1.0.1, tablet@0.1.4, th3dungeon@0.2.0, translatablebooks@1.1.0, vinconomy@0.1.6, creative@1.18.15, vsinstruments@1.2.4, survival@1.18.15, metalrecovery@0.1.19-pre.1, bullseye@2.5.1, cats@1.8.0, chemistrylib@1.1.5, em@2.4.1, feverstonewilds@1.4.5, linearpower@0.2.1, morecandles@1.1.3, playercorpse@1.8.0, simplewinddirection@1.0.2, stonequarry@3.1.7, wolftaming@1.8.0, bricklayers@2.4.0, kosfire@1.1.3, kos-goldamalgam@1.0.0, kosphotography@1.3.4, moreroads@1.5.4, tailorsdelight@1.2.2
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.Client.NoObf.TextureAtlasManager.get_Item(AssetLocation textureLocation) in VintagestoryLib\Client\Render\Atlas\TextureAtlasManager.cs:line 53
   at Vintagestory.GameContent.BlockEntityDisplay.getOrCreateTexPos(AssetLocation texturePath) in VSSurvivalMod\BlockEntity\BEContainerDisplay.cs:line 112
   at Vintagestory.GameContent.BlockEntityDisplay.get_Item(String textureCode) in VSSurvivalMod\BlockEntity\BEContainerDisplay.cs:line 87
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElement(Int32 indexForLogging, MeshData meshdata, ShapeElement element, TesselationMetaData meta) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 394
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements(MeshData meshdata, ShapeElement[] elements, TesselationMetaData meta) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 306
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements(MeshData meshdata, ShapeElement[] elements, TesselationMetaData meta) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 306
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(Shape shapeBase, MeshData& modeldata, Vec3f wholeMeshRotation, Vec3f wholeMeshOffset, Single wholeMeshScale, TesselationMetaData meta) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 302
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(String type, AssetLocation name, CompositeShape compositeShape, MeshData& modeldata, ITexPositionSource texSource, Int32 generalGlowLevel, Byte climateColorMapIndex, Byte seasonColorMapIndex, Nullable`1 quantityElements, String[] selectiveElements) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 51
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateItem(Item item, MeshData& modeldata, ITexPositionSource texSource) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 620
   at Vintagestory.GameContent.BlockEntityDisplay.getOrCreateMesh(ItemStack stack, Int32 index) in VSSurvivalMod\BlockEntity\BEContainerDisplay.cs:line 204
   at Vintagestory.GameContent.BlockEntityDisplay.updateMesh_Patch1(BlockEntityDisplay this, Int32 index)
   at PrimitiveSurvival.ModSystem.BETreeHollowGrown.updateMeshes()
   at Vintagestory.GameContent.BlockEntityDisplayCase.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldForResolving) in VSSurvivalMod\BlockEntity\BEDisplayCase.cs:line 203
   at PrimitiveSurvival.ModSystem.BETreeHollowGrown.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldForResolve)
   at Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(Packet_BlockEntity p, ClientMain game) in VintagestoryLib\Client\Model\ClientChunk.cs:line 429
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 414
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 757
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 14/01/2024 23:11:57, Site = , Source = Windows Error Reporting, Message = Fault bucket 2007150627803250050, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFC55.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER118.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER139.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER146.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER166.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_54bdf1bb-2368-4a36-9707-456857e92a24

Analysis symbol: 
Rechecking for solution: 0
Report Id: e34a53e9-c099-4c3d-b148-94d2978f50bf
Report Status: 268566528
Hashed bucket: 38dd2bbe130a69d3fbdad4dc94ea3d82
Cab Guid: 0 }
--------------
{ TimeGenerated = 14/01/2024 23:11:55, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.15.0, time stamp: 0x64e841c5
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process ID: 0xcd68
Faulting application start time: 0x01da4735c58a4fcc
Faulting application path: C:\Users\\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report ID: e34a53e9-c099-4c3d-b148-94d2978f50bf
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 14/01/2024 22:29:24, Site = , Source = Windows Error Reporting, Message = Fault bucket 2007150627803250050, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB37.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC61.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC91.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC91.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCB1.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_53079e6c-dccd-4408-a93b-bb6902c5a71c

Analysis symbol: 
Rechecking for solution: 0
Report Id: 4bcd7ff5-3438-45bc-9032-3416c49405e0
Report Status: 268566528
Hashed bucket: 38dd2bbe130a69d3fbdad4dc94ea3d82
Cab Guid: 0 }
```

**Comment by SpearAndFang** [comment]
I believe this is a conflict with the In Dappled Groves mod.
